### ISSUE TITLE
Add extra fields to STORE messages

### ISSUE THREAD

**Issue by MHHukiewitz** [aleph-im/aleph-sdk-ts#171]
> Store message type / send are missing extrafields, that is supported on the python sdk. I don't think it's blocking for me atm
@philogicae

See: https://github.com/aleph-im/aleph-sdk-python/blob/main/src/aleph/sdk/client/authenticated_http.py#L347

**Comment by teezzan** [comment]
@MHHukiewitz, please check this out.
