### ISSUE TITLE
Outdated docs links

### ISSUE THREAD

**Issue by RezaRahemtola** [aleph-im/aleph-sdk-ts#175]
**Describe the bug**
Due to the "reset" to v1.0, running installation commands can be confusing

**To Reproduce**
```sh
npm install aleph-sdk-ts  # Installs v3.9.2
npm install aleph-sdk-ts@latest  # Installs v3.9.2
npm install aleph-sdk-ts@1.0.6  # Installs the correct current version
```

**Expected behavior**
It should installs the right version without having to specify the exact version, this can cause a lot of mistakes from developers discovering Aleph (especially since this issue will persist until the new versioning exceeds the old one of 3.9.2, which will probably take a long time).

**Environment**
/

**Additional context**
I know it's more an npm issue than Aleph, but should be address in some way nonetheless imo

**Comment by RezaRahemtola** [comment]
cc @MHHukiewitz :smile:

**Comment by RezaRahemtola** [comment]
my bad, it's just the information that isn't correct on:
- The README that stills gives the old installation command
- The links in both this README and the repository that still points to an old documentation page instead of https://docs.aleph.im/libraries/typescript-sdk/

I could make a PR but don't know if you want to keep the GitHub pages link too as it also contains the (correct) API reference inside it, so I'll let you handle it as you like :smile:

**Comment by RezaRahemtola** [comment]
Maybe marking the old package on npm: https://www.npmjs.com/package/aleph-sdk-ts as deprecated (https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions/) could be great too

**Comment by philogicae** [comment]
https://github.com/aleph-im/aleph-sdk-ts/pull/185
