### ISSUE TITLE
Add support for Solana wallets

### ISSUE THREAD

**Issue by hoh** [aleph-im/aleph-sdk-ts#25]
As a developer using the SDK, I would like to allow users of my app to connect with their Solana wallet.

Solana accounts only support key pairs, not connections to wallets yet.
https://github.com/aleph-im/aleph-sdk-ts/blob/main/src/accounts/solana.ts#L15

## Relevant documentation
https://solanacookbook.com/references/keypairs-and-wallets.html#how-to-generate-a-new-keypair
https://github.com/solana-labs/wallet-adapter

**Comment by BjrInt** [comment]
dupplicate of: #16
