### ISSUE TITLE
Add support for request proxying via CRN host

### ISSUE THREAD

**Issue by hoh** [aleph-im/aleph-sdk-ts#35]
## Context

- A Compute Resource Node runs virtual machines ("VM") configured by the aleph-vm vm_supervisor ("supervisor"). 
- A VM can be configured with or without internet access
- A VM can be configured with or without Aleph API access
- The supervisor provides an API proxy that permits a VM without internet access to still access Aleph APIs
- A VM should not hardcode which Aleph API endpoint it is using, that configuration should come from the supervisor.

This is already working in the Python [aleph-client](https://github.com/aleph-im/aleph-client/), but not in the TypeScript SDK.

## Method

A [socat](https://manpages.org/socat) process is created during the boot of an Aleph VM ([source](https://github.com/aleph-im/aleph-vm/blob/55b4abe0600fd8a2903914e4b4a59fbbb0c4888d/runtimes/aleph-alpine-3.13-python/init0.sh#L43)) and creates a UNIX socket on `/tmp/socat-socket`. HTTP requests to that socket are forwarded to the [guest_api](https://github.com/aleph-im/aleph-vm/blob/76afc09a9fc56bcef01c52afde846ae64200b731/guest_api/__main__.py) process on the host and then dispatched depending on the route.

User processes can send HTTP requests on that socket instead of using TCP/IP. The host "localhost" may need to be used.

The following environment variables are [set inside the VM](https://github.com/aleph-im/aleph-vm/blob/bd438d1c94ff4dbd023c7bdfe197e4a932f28d10/runtimes/aleph-alpine-3.13-python/init1.py#L89-L92) and should be read by the SDK to determine how to connect to the guest API via this unix socket:

```python
os.environ["ALEPH_API_HOST"] = "http://localhost"
os.environ["ALEPH_API_UNIX_SOCKET"] = "/tmp/socat-socket"
os.environ["ALEPH_REMOTE_CRYPTO_HOST"] = "http://localhost"
os.environ["ALEPH_REMOTE_CRYPTO_UNIX_SOCKET"] = "/tmp/socat-socket"
```

**Comment by BjrInt** [comment]
dupplicate of #27
