### ISSUE TITLE
What are the recommended and the supported versions of node ?

### ISSUE THREAD

**Issue by hoh** [aleph-im/aleph-sdk-ts#66]
I do not see any reference to the recommended or supported of Node. 

Is 14 supported ? What about 16 and 18 ?
Do we want automatic tests on all supported versions ?

Note that tests do pass with in a `docker node:14` container.

**Comment by BjrInt** [comment]
As a rule of thumb we should always support LTS ([currently 16, until october](https://github.com/nodejs/release#release-schedule), then 18). 
With the dockerized environment it makes no sense to support versions from 5 years ago, but we could indeed run tests in the 3 previous versions.

:warning: Tezos, according to [this](https://github.com/aleph-im/aleph-sdk-ts/blob/account/tezos/package.json#L23), does not support v18 so we should watch that out

**Comment by BjrInt** [comment]
Preliminary testing shows that it sucessfully runs from v12 to v16. Should we add a github action to ensure this remains the case?
